version: '3'
services:
  backend:
    build:
      context: "./backend"
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: "./frontend"
    ports:
      - "80:80"

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
