
DROP TABLE IF EXISTS CARTELERA_PASES;
DROP TABLE IF EXISTS CARTELERA_PELICULAS;
DROP TABLE IF EXISTS CARTELERA_CLASIFICACIONES;
DROP TABLE IF EXISTS CARTELERA_SALAS;
DROP TABLE IF EXISTS CARTELERA_CINES;

CREATE TABLE CARTELERA_CINES
	(
	CINE_ID INTEGER NOT NULL AUTO_INCREMENT ,
	CINE VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(CINE_ID)  
	);

CREATE TABLE CARTELERA_SALAS
	(
	SALA_ID INTEGER NOT NULL AUTO_INCREMENT ,
	CINE_ID INTEGER NOT NULL  ,
	SALA VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(SALA_ID),
	FOREIGN KEY ( CINE_ID ) REFERENCES CARTELERA_CINES( CINE_ID ) 
	);
	
CREATE TABLE CARTELERA_CLASIFICACIONES
	(
	CLASIFICACION_ID INTEGER NOT NULL AUTO_INCREMENT,
	CLASIFICACION VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(CLASIFICACION_ID)
	);

CREATE TABLE CARTELERA_PELICULAS
	(
	PELICULA_ID INTEGER NOT NULL AUTO_INCREMENT,
	CLASIFICACION_ID INTEGER NOT NULL ,
	TITULO VARCHAR(10)  NOT NULL ,
	PRIMARY KEY(PELICULA_ID),
	FOREIGN KEY ( CLASIFICACION_ID ) REFERENCES CARTELERA_CLASIFICACIONES( CLASIFICACION_ID ) 
	);

CREATE TABLE CARTELERA_PASES
	(
	PASE_ID INTEGER NOT NULL AUTO_INCREMENT,
	PELICULA_ID INTEGER NOT NULL ,
	SALA_ID INTEGER NOT NULL ,
	HORA TIME,
	PRIMARY KEY(PASE_ID),
	FOREIGN KEY ( PELICULA_ID ) REFERENCES CARTELERA_PELICULAS( PELICULA_ID ),
	FOREIGN KEY ( SALA_ID ) REFERENCES CARTELERA_SALAS( SALA_ID ) 
	);
		
INSERT INTO CARTELERA_CINES ( CINE ) VALUES ( 'REX');
INSERT INTO CARTELERA_CINES ( CINE ) VALUES ( 'COLISEUM');
INSERT INTO CARTELERA_CINES ( CINE ) VALUES ( 'METROPOL');


INSERT INTO CARTELERA_SALAS ( CINE_ID, SALA ) VALUES ( 1, "SALA A");
INSERT INTO CARTELERA_SALAS ( CINE_ID, SALA ) VALUES ( 1, "SALA B");
INSERT INTO CARTELERA_SALAS ( CINE_ID, SALA ) VALUES ( 2, "SALA A");
INSERT INTO CARTELERA_SALAS ( CINE_ID, SALA ) VALUES ( 2, "SALA B");
INSERT INTO CARTELERA_SALAS ( CINE_ID, SALA ) VALUES ( 3, "SALA A");
INSERT INTO CARTELERA_SALAS ( CINE_ID, SALA ) VALUES ( 3, "SALA B");


INSERT INTO CARTELERA_CLASIFICACIONES ( CLASIFICACION ) VALUES ( "TP");
INSERT INTO CARTELERA_CLASIFICACIONES ( CLASIFICACION ) VALUES ( "13");
INSERT INTO CARTELERA_CLASIFICACIONES ( CLASIFICACION ) VALUES ( "18");
INSERT INTO CARTELERA_CLASIFICACIONES ( CLASIFICACION ) VALUES ( "R");

INSERT INTO CARTELERA_PELICULAS ( TITULO, CLASIFICACION_ID ) VALUES ( "LO QUE EL VIENTO SE LLEVO", 1);
INSERT INTO CARTELERA_PELICULAS ( TITULO, CLASIFICACION_ID ) VALUES ( "EMANUELLE", 4);
INSERT INTO CARTELERA_PELICULAS ( TITULO, CLASIFICACION_ID ) VALUES ( "SPIDERMAN", 3);
INSERT INTO CARTELERA_PELICULAS ( TITULO, CLASIFICACION_ID ) VALUES ( "TOY STORY", 1);
INSERT INTO CARTELERA_PELICULAS ( TITULO, CLASIFICACION_ID ) VALUES ( "ELECTRA", 1);
INSERT INTO CARTELERA_PELICULAS ( TITULO, CLASIFICACION_ID ) VALUES ( "LA PANTERA ROSA", 1);

INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 1, 1, "16:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 1, 1, "17:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 1, 1, "18:00" );

INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 2, 2, "16:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 2, 2, "17:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 2, 2, "18:00" );



INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 4, 1, "16:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 4, 1, "17:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 4, 1, "18:00" );

INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 3, 2, "16:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 3, 2, "17:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 3, 2, "18:00" );



INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 5, 3, "16:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 5, 3, "17:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 5, 3, "18:00" );

INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 6, 4, "16:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 6, 4, "17:00" );
INSERT INTO CARTELERA_PASES ( PELICULA_ID, SALA_ID, HORA ) VALUES ( 6, 4, "18:00" );
